apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spurtedu
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    path: /metrics
    enabled: true
  secureLogs:
    enabled: true
  ingresses:
  {{# each ingress as |i| }}
    - {{i}}
  {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: spammer
        - application: spaghet
        - application: spanner
        - application: spoiler
  azure:
    sidecar:
      enabled: true
      autoLogin: false
    application:
      tenant: nav.no
      enabled: true
      allowAllUsers: true
  valkey:
    - instance: oppslag
      access: readwrite
